include(CMakeParseArguments)

set(CTM_CLASSIC_CONTENTS
    "BORDER_TOP,BORDER_LEFT,BORDER_RIGHT,BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #0
    "BORDER_TOP,BORDER_LEFT,BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #1
    "BORDER_TOP,BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #2
    "BORDER_TOP,BORDER_RIGHT,BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #3
    "BORDER_TOP,BORDER_LEFT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #4
    "BORDER_TOP,BORDER_RIGHT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #5
    "BORDER_LEFT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #6
    "BORDER_TOP,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #7
    "CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT" #8
    "CORNER_BOTTOMLEFT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #9
    "CORNER_BOTTOMRIGHT,CORNER_TOPRIGHT" #10
    "CORNER_BOTTOMRIGHT,CORNER_BOTTOMLEFT" #11
    "BORDER_TOP,BORDER_LEFT,BORDER_RIGHT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #12
    "BORDER_TOP,BORDER_LEFT,CORNER_BOTTOMLEFT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #13
    "BORDER_TOP,CORNER_TOPLEFT,CORNER_TOPRIGHT" #14
    "BORDER_TOP,BORDER_RIGHT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #15
    "BORDER_LEFT,BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #16
    "BORDER_RIGHT,BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #17
    "BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #18
    "BORDER_RIGHT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #19
    "CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPRIGHT" #20
    "CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #21
    "CORNER_BOTTOMLEFT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #22
    "CORNER_BOTTOMLEFT,CORNER_TOPLEFT" #23
    "BORDER_LEFT,BORDER_RIGHT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #24
    "BORDER_LEFT,CORNER_TOPLEFT,CORNER_BOTTOMLEFT" #25
    "" #26
    "BORDER_RIGHT,CORNER_TOPRIGHT,CORNER_BOTTOMRIGHT" #27
    "BORDER_LEFT,CORNER_TOPLEFT,CORNER_TOPRIGHT,CORNER_BOTTOMLEFT" #28
    "BORDER_TOP,CORNER_TOPLEFT,CORNER_TOPRIGHT,CORNER_BOTTOMLEFT" #29
    "BORDER_LEFT,CORNER_TOPLEFT,CORNER_TOPRIGHT,CORNER_BOTTOMLEFT" #30
    "BORDER_LEFT,CORNER_TOPLEFT,CORNER_TOPRIGHT,CORNER_BOTTOMLEFT" #31
    "CORNER_BOTTOMRIGHT" #32
    "CORNER_BOTTOMLEFT" #33
    "CORNER_TOPLEFT,CORNER_BOTTOMRIGHT" #34
    "CORNER_BOTTOMLEFT,CORNER_TOPRIGHT" #35
    "BORDER_BOTTOM,BORDER_LEFT,BORDER_RIGHT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #36
    "BORDER_BOTTOM,BORDER_LEFT,CORNER_BOTTOMLEFT,CORNER_TOPLEFT,CORNER_BOTTOMRIGHT" #37
    "BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT" #38
    "BORDER_BOTTOM,BORDER_RIGHT,CORNER_BOTTOMRIGHT,CORNER_BOTTOMLEFT,CORNER_TOPRIGHT" #39
    "BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT" #40
    "BORDER_RIGHT,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPRIGHT" #41
    "BORDER_BOTTOM,CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPRIGHT" #42
    "BORDER_RIGHT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #43
    "CORNER_TOPRIGHT" #44
    "CORNER_TOPLEFT" #45
    "CORNER_BOTTOMLEFT,CORNER_BOTTOMRIGHT,CORNER_TOPLEFT,CORNER_TOPRIGHT" #46
)

set(CTM_PARTS BORDER_BOTTOM BORDER_LEFT BORDER_RIGHT BORDER_TOP CORNER_BOTTOMLEFT CORNER_BOTTOMRIGHT CORNER_TOPLEFT CORNER_TOPRIGHT)

function(add_ctm_texture)
    
    macro(part_to_variant _OUT_VARIABLE)
        set(${_OUT_VARIABLE} "")
        foreach(part ${ARGN})
            list(APPEND ${_OUT_VARIABLE} ${__${part}})
        endforeach()
    endmacro()
    
    set(OVA TARGET SOURCE PROPERTIES_FILE ${CTM_PARTS})
            
    cmake_parse_arguments(_ "" "${OVA}" "" ${ARGN})
    
    set(DESTINATION "${__TARGET}")
    list_xcf_layers_raw("${CMAKE_CURRENT_LIST_DIR}/${__SOURCE}" LAYERS)
    
    set(BUILD_DESTINATIONS "")
    
    foreach(i RANGE 46)
        list(GET CTM_CLASSIC_CONTENTS ${i} tile_contents)
        string(REPLACE "," ";" tile_contents "${tile_contents}")
        
        set(remaining_parts ${CTM_PARTS})
        list(REMOVE_ITEM remaining_parts "" ${tile_contents})
        
        part_to_variant(tile_variants ${tile_contents})
        part_to_variant(remaining_variants ${remaining_parts})
        
        request_layer_list(OUTPUT_VARIABLE variant_layers
            LAYER_LIST ${LAYERS}
            ADD ${tile_variants}
            REMOVE ${remaining_variants})
        
        get_filename_component(SOURCE_NAME "${__SOURCE}" NAME)
        build_destination(BUILD_DESTINATION "${__SOURCE}" "-${i}")
        
        add_xcf_file("${CMAKE_CURRENT_LIST_DIR}/${__SOURCE}" "mcpatcher/ctm/${DESTINATION}/${i}.png" "Rendering CTM texture ${SOURCE_NAME} (#${i})" "-${i}" ${variant_layers})
        list(APPEND BUILD_DESTINATIONS "${CMAKE_CURRENT_LIST_DIR}/${BUILD_DESTINATION}")
        
    endforeach()
    
    add_custom_target("${__TARGET}" ALL
                    DEPENDS ${BUILD_DESTINATIONS})
                    
    install(FILES "${CMAKE_CURRENT_LIST_DIR}/${__PROPERTIES_FILE}" DESTINATION "pack/assets/minecraft/mcpatcher/ctm/${DESTINATION}/")
    
endfunction()
